/**
 * Code generator for telegram.js.
 *
 * Reads the machine-readable Telegram Bot API spec (vendor/api.json, sourced from
 * https://github.com/PaulSonOfLars/telegram-bot-api-spec) and emits the fully-typed
 * "generated core": every Bot API object type and every method signature.
 *
 * Usage:
 *   node scripts/generate.ts            # generate from the pinned vendor/api.json
 *   node scripts/generate.ts --fetch    # download the latest spec first, then generate
 *
 * The emitted files under src/generated/ are the single source of truth for the wire
 * shapes. They are committed; regenerate (and bump vendor/api.json) to track new Bot
 * API versions. Never edit them by hand.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SPEC_PATH = join(ROOT, 'vendor', 'api.json');
const OUT_DIR = join(ROOT, 'src');
const SPEC_URL = 'https://raw.githubusercontent.com/PaulSonOfLars/telegram-bot-api-spec/main/api.json';

interface SpecField {
  name: string;
  types: string[];
  required: boolean;
  description: string;
}
interface SpecType {
  name: string;
  href: string;
  description: string[];
  fields?: SpecField[];
  subtypes?: string[];
}
interface SpecMethod {
  name: string;
  href: string;
  description: string[];
  returns: string[];
  fields?: SpecField[];
}
interface Spec {
  version: string;
  release_date: string;
  changelog: string;
  types: Record<string, SpecType>;
  methods: Record<string, SpecMethod>;
}

const HEADER = (spec: Spec) => `/* eslint-disable */
// prettier-ignore-start
/**
 * AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT BY HAND.
 * Source: ${spec.version} (${spec.release_date})
 * Spec: https://github.com/PaulSonOfLars/telegram-bot-api-spec
 */
`;

/** Map a single Bot API type token to a TypeScript type expression. */
function tsType(apiType: string): string {
  if (apiType.startsWith('Array of ')) return `${tsType(apiType.slice('Array of '.length))}[]`;
  switch (apiType) {
    case 'Integer':
    case 'Float':
      return 'number';
    case 'String':
      return 'string';
    case 'Boolean':
      return 'boolean';
    case 'True':
      return 'true';
    case 'False':
      return 'false';
    default:
      return apiType; // reference to another generated type
  }
}

/** Union of the accepted types for a field, deduplicated. */
function fieldType(field: SpecField): string {
  const parts = [...new Set(field.types.map(tsType))];
  return parts.join(' | ');
}

/** Try to extract a fixed discriminator literal (e.g. `type` is always "photo"). */
function discriminatorLiteral(field: SpecField): string | null {
  if (!field.required || field.types.length !== 1 || field.types[0] !== 'String') return null;
  if (!['type', 'status', 'source'].includes(field.name)) return null;
  const m = field.description.match(/(?:always|must be)\s+"?([A-Za-z_]+)"?/);
  return m ? `'${m[1]}'` : null;
}

function jsdoc(lines: string[], indent = ''): string {
  const clean = lines.join(' ').replace(/\s+/g, ' ').trim();
  if (!clean) return '';
  const wrapped: string[] = [];
  let line = '';
  for (const word of clean.split(' ')) {
    if ((line + word).length > 110) {
      wrapped.push(line.trimEnd());
      line = '';
    }
    line += word + ' ';
  }
  if (line.trim()) wrapped.push(line.trimEnd());
  return `${indent}/**\n${wrapped.map(l => `${indent} * ${l}`).join('\n')}\n${indent} */\n`;
}

function key(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : `'${name}'`;
}

function renderFields(fields: SpecField[], indent: string): string {
  return fields
    .map(f => {
      const literal = discriminatorLiteral(f);
      const type = literal ?? fieldType(f);
      const optional = f.required ? '' : '?';
      return `${jsdoc([f.description], indent)}${indent}${key(f.name)}${optional}: ${type};`;
    })
    .join('\n\n');
}

function generateTypes(spec: Spec): string {
  const out: string[] = [HEADER(spec)];
  const names = Object.keys(spec.types).sort();

  for (const name of names) {
    const t = spec.types[name]!;

    // Polymorphic parent -> union of subtypes. Subtypes are usually plain type names,
    // but a few (e.g. RichText) mix in scalars like `String` or `Array of RichText`.
    if (t.subtypes && t.subtypes.length) {
      const union = [...new Set(t.subtypes.map(tsType))].join(' | ');
      out.push(`${jsdoc(t.description)}export type ${name} = ${union};`);
      continue;
    }

    // The special file-upload sentinel.
    if (name === 'InputFile') {
      out.push(
        `${jsdoc(t.description)}export type InputFile = Blob | Buffer | NodeJS.ReadableStream | { name: string; data: Blob | Buffer | NodeJS.ReadableStream };`,
      );
      continue;
    }

    // Objects with no fields -> empty object (service messages, placeholders).
    if (!t.fields || t.fields.length === 0) {
      out.push(`${jsdoc(t.description)}export type ${name} = Record<string, never>;`);
      continue;
    }

    out.push(`${jsdoc(t.description)}export interface ${name} {\n${renderFields(t.fields, '  ')}\n}`);
  }

  return out.join('\n\n') + '\n';
}

function generateMethods(spec: Spec): string {
  const out: string[] = [HEADER(spec)];
  out.push(`import type * as T from './types.js';`);

  const names = Object.keys(spec.methods).sort();
  const paramInterfaces: string[] = [];
  const methodSignatures: string[] = [];
  const fileFields: Record<string, string[]> = {};

  for (const name of names) {
    const m = spec.methods[name]!;
    const paramName = `${name[0]!.toUpperCase()}${name.slice(1)}Params`;
    const ret = m.returns.map(tsType).join(' | ') || 'unknown';
    const retExpr = qualify(ret);

    const fields = m.fields ?? [];
    const filesInMethod = fields.filter(f => f.types.some(x => x.replace('Array of ', '') === 'InputFile'));
    if (filesInMethod.length) fileFields[name] = filesInMethod.map(f => f.name);

    if (fields.length === 0) {
      methodSignatures.push(`${jsdoc(m.description, '  ')}  ${name}(): Promise<${retExpr}>;`);
      continue;
    }

    const body = fields
      .map(f => {
        const literal = discriminatorLiteral(f);
        const type = literal ?? qualify(fieldType(f));
        const optional = f.required ? '' : '?';
        return `${jsdoc([f.description], '  ')}  ${key(f.name)}${optional}: ${type};`;
      })
      .join('\n\n');
    paramInterfaces.push(`export interface ${paramName} {\n${body}\n}`);

    const allOptional = fields.every(f => !f.required);
    const paramArg = allOptional ? `params?: ${paramName}` : `params: ${paramName}`;
    methodSignatures.push(`${jsdoc(m.description, '  ')}  ${name}(${paramArg}): Promise<${retExpr}>;`);
  }

  out.push(paramInterfaces.join('\n\n'));
  out.push(
    `/**\n * Every Telegram Bot API method, fully typed. Implemented by the raw client (\`bot.api\`).\n */\nexport interface ApiMethods {\n${methodSignatures.join('\n\n')}\n}`,
  );
  out.push(
    `/** Fields, per method, that may carry an uploadable {@link T.InputFile} (used for multipart detection). */\nexport const METHOD_FILE_FIELDS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(
      fileFields,
      null,
      2,
    )} as const;`,
  );

  return out.join('\n\n') + '\n';
}

/** Prefix bare generated type references with the `T.` namespace import. */
function qualify(expr: string): string {
  return expr.replace(/[A-Za-z_][A-Za-z0-9_]*/g, tok => {
    if (['number', 'string', 'boolean', 'true', 'false', 'unknown', 'Blob', 'Buffer', 'NodeJS'].includes(tok))
      return tok;
    return `T.${tok}`;
  });
}

function generateMetadata(spec: Spec): string {
  const methodNames = Object.keys(spec.methods).sort();
  const typeNames = Object.keys(spec.types).sort();
  return (
    HEADER(spec) +
    `\nexport const API_VERSION = ${JSON.stringify(spec.version)} as const;\n` +
    `export const API_RELEASE_DATE = ${JSON.stringify(spec.release_date)} as const;\n` +
    `export const API_CHANGELOG = ${JSON.stringify(spec.changelog)} as const;\n\n` +
    `/** Names of every Bot API method covered by the generated client. */\n` +
    `export const METHOD_NAMES = ${JSON.stringify(methodNames)} as const;\n\n` +
    `/** Names of every Bot API object type. */\n` +
    `export const TYPE_NAMES = ${JSON.stringify(typeNames)} as const;\n`
  );
}

async function main() {
  if (process.argv.includes('--fetch')) {
    process.stdout.write(`Fetching latest spec from ${SPEC_URL} ...\n`);
    const res = await fetch(SPEC_URL);
    if (!res.ok) throw new Error(`Failed to fetch spec: ${res.status} ${res.statusText}`);
    await writeFile(SPEC_PATH, await res.text());
  }

  const spec: Spec = JSON.parse(await readFile(SPEC_PATH, 'utf8'));
  process.stdout.write(`Generating from ${spec.version} (${spec.release_date})\n`);

  await writeFile(join(OUT_DIR, 'types.ts'), generateTypes(spec));
  await writeFile(join(OUT_DIR, 'methods.ts'), generateMethods(spec));
  await writeFile(join(OUT_DIR, 'metadata.ts'), generateMetadata(spec));

  process.stdout.write(
    `Wrote ${Object.keys(spec.types).length} types and ${Object.keys(spec.methods).length} methods to src/generated/\n`,
  );
}

main().catch(err => {
  process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
